name: Daily players.json update

on:
  schedule:
    - cron: '0 6 * * *'    # every day at 06:00 UTC
  workflow_dispatch:      # allows manual trigger

jobs:
  update-players:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Fetch latest players.json
        run: node scripts/fetch-players.js

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add players.json
          if git diff --cached --quiet; then
            echo "No changes in players.json"
            exit 0
          fi
          git commit -m "chore: daily update of players.json"
          git push
